### ISSUE TITLE
upgrade to 4.7.1

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodcoops.net#43]
I have read [the instructions](https://github.com/foodcoops/foodcoops.net#upgrading-foodsoft). I believe that the small upgrade from 4.7.0 to 4.7.1 is much simpler than that: Just running `deploy.sh` should suffice because (1) the docker image `foodcoops/foodsoft:4.7` has already been updated to 4.7.1 on docker hub and (2) there are no database migrations.

- [x] manual database backup, see #41
- [x] deploy
- [x] post-upgrade announcement (where?)
  - [x] [foodcoops-announce@wat.systemausfall.org](http://foodsoft.51229.x6.nabble.com/foodsoft-global-announce-f1511.html) (see also #42)
  - [x] https://foodcoops.net/ (see foodcoops/foodcoops.github.io#3)

**Comment by JuliusR** [comment]
The upgrade is mostly done, but I need help with foodcoops/foodcoops.github.io#3.

**Comment by JuliusR** [comment]
Done :tada:
